# Generated by Django 5.2.4 on 2025-07-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('Username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
    ]
